name: rde-detectron2
channels:
  - pytorch
  - mcs07
  - chemdataextractor
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - aom=3.2.0=h9c3ff4c_2
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha00ac49_1009
  - cffi=1.15.0=py38hd667e15_1
  - cirpy=1.0.2=py_2
  - cpuonly=2.0=0
  - dbus=1.13.6=h5008d03_3
  - expat=2.4.4=h9c3ff4c_0
  - ffmpeg=4.3.2=h37c90e5_3
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=ha180cfb_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h9c3ff4c_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.19.8.1=h73d1719_1008
  - gevent=21.12.0=py38h0a891b7_1
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=1.1.2=py38hfa26641_2
  - gst-plugins-base=1.18.5=hf529b03_3
  - gstreamer=1.18.5=h9f60fe5_3
  - harfbuzz=3.3.1=hb4a5f5f_0
  - hdf5=1.12.1=nompi_h2750804_103
  - icu=69.1=h9c3ff4c_0
  - imageio=2.14.1=pyh239f2a4_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jasper=2.0.33=ha77e612_0
  - jbig=2.1=h7f98852_2003
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - krb5=1.19.2=hcc1bbae_3
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - leptonica=1.82.0=h950d820_0
  - lerc=3.0=h9c3ff4c_0
  - libarchive=3.5.2=hccf745f_1
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.81.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libdrm=2.4.109=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libglib=2.70.2=h174f98d_2
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=11.2.0=h1d223b6_12
  - libiconv=1.16=h516909a_0
  - libimagequant=2.17.0=h7f98852_1
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm13=13.0.1=hf817b99_0
  - libnghttp2=1.46.0=h812cca2_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.5=py38hd60e7aa_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libpq=14.1=hd57d9b9_1
  - libprotobuf=3.19.4=h780b84a_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libva=2.13.0=h7f98852_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - mysql-common=8.0.28=ha770c72_0
  - mysql-libs=8.0.28=hfa10184_0
  - ncurses=6.3=h9c3ff4c_0
  - nettle=3.6=he412f7d_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.74=hb5efdd6_0
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - opencv=4.5.5=py38h578d9bd_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - pcre=8.45=h9c3ff4c_0
  - pebble=4.6.3=pyhd8ed1ab_0
  - pillow=9.0.1=py38he2f12e7_0
  - pip=22.0.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.5=py38he5a9106_0
  - pycparser=2.21=pyhd8ed1ab_0
  - python=3.8.12=ha38a3c6_3_cpython
  - python_abi=3.8=2_cp38
  - pytorch=1.10.2=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - qt=5.12.9=ha98a1a1_5
  - readline=8.1=h46c0cb4_0
  - scikit-learn=1.0.2=py38h1561384_0
  - scipy=1.8.0=py38h56a6a73_1
  - setuptools=60.8.1=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - svt-av1=0.9.0=h9c3ff4c_0
  - tesseract=4.1.1=h84e3e21_6
  - tesserocr=2.5.1=py38h709712a_2
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.11=h27826a3_1
  - torchvision=0.11.3=py38_cpu
  - typing_extensions=4.0.1=pyha770c72_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h4bd325d_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
  - zope.event=4.5.0=pyh9f0ad1d_0
  - zope.interface=5.4.0=py38h0a891b7_2
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - black==21.4b2
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.11
    - click==8.0.3
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - detectron2==0.6+cpu
    - fonttools==4.29.1
    - future==0.18.2
    - fvcore==0.1.5.post20220119
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - hydra-core==1.1.1
    - idna==3.3
    - importlib-metadata==4.10.1
    - importlib-resources==5.4.0
    - iopath==0.1.9
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mypy-extensions==0.4.3
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - packaging==21.3
    - pathspec==0.9.0
    - portalocker==2.3.2
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pydot==1.4.2
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - regex==2022.1.18
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - toml==0.10.2
    - tqdm==4.62.3
    - urllib3==1.26.8
    - werkzeug==2.0.3
    - yacs==0.1.8
    - zipp==3.7.0
prefix: /home/damian/miniconda3/envs/rde-detectron2
